name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify the Python version you need

      - name: Install MkDocs and dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material  # Install the Material theme or any other plugins you use

      - name: Build the documentation
        run: mkdocs build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # The default output directory for MkDocs
